apiVersion: apps/v1
kind: Deployment
metadata:
  name: tw
  labels:
    app: tw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tw
  template:
    metadata:
      labels:
        app: tw
    spec:
      containers:
      - name: nginx
        image: python-app2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30005
  selector:
    app: tw
