apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  app: redis-pod
  namespace: gcp-final-task
  labels:
    name: redis-pod
spec:
  containers:
  - name: redis
    image: gcr.io/omars-project-367822/redis:latest
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: gcp-final-task
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-pod


